apiVersion: v1
kind: Service
metadata:
  labels:
    app: orbit-test
  name: orbit-test
spec:
  ports:
  - port: 81
    protocol: TCP
    targetPort: 8190
  selector:
    app: orbit-test
  type: LoadBalancer
status:
  loadBalancer: {}