apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: orbit-app
  name: orbit-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orbit-app
  strategy: {}
  template:
    metadata:
      labels:
        app: orbit-app
    spec:
      containers:
        - image: {{ .Values.env.containers.image }}
          name: orbit-app
          env:
            - name: spring.datasource.url
              value: {{ .Values.env.database.url }}
            - name: spring.datasource.username
              value: {{ .Values.env.database.username }}
            - name: spring.datasource.password
              value: {{ .Values.env.database.password }}