apiVersion: v1
kind: Service
metadata:
  labels:
    app: orbit-app
  name: orbit-app
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: orbit-app
  type: LoadBalancer
status:
  loadBalancer: {}